name: ci.yml
on:
  push: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      FAKE_DEV: /dev/fake-dev0
      TEST_VOL: ${{ github.workspace }}/test
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: 'false'

      - name: Create virtual block device
        run: |
          # create a 100M file that'll be used by the loopback device
          dd if=/dev/zero of=$RUNNER_TEMP/dev0-backstore bs=1M count=200
          
          # create the loopback block device
          # 200 hopefully won't collide with `ls -l /dev/loop*`
          sudo mknod "$FAKE_DEV" b "$(grep 'loop' /proc/devices | awk '{print $1}')" 200
          
          sudo losetup "$FAKE_DEV" "$RUNNER_TEMP/dev0-backstore"

      - name: Create BTRFS volume
        run: |
          sudo mkfs.btrfs $FAKE_DEV
          mkdir $TEST_VOL
          sudo mount $FAKE_DEV $TEST_VOL

      - name: Test
        run: |
          df -h
