name: ci.yml
on:
  push: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      FAKE_DEV: /dev/fake-dev0
      ROOT_VOL: ${{ github.workspace }}/test/root
      TEST_SUBVOL: ${{ github.workspace }}/test/subvol
      TEST_SUBVOL_NAME: ".subvol"
      CONTENT: "hello, world"

      RESTIC_REPOSITORY: ${{ github.workspace }}/test/backup
      RESTIC_PASSWORD: secure-password
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: 'false'

      - name: Create virtual block device
        run: .github/create_block_device.sh "$RUNNER_TEMP/dev0-backstore" "$FAKE_DEV"

      - name: Create BTRFS volume
        run: .github/create_btrfs_volume.sh "$FAKE_DEV" "$ROOT_VOL"

      - name: Create BTRFS subvolume
        run: .github/create_btrfs_subvolume.sh "$FAKE_DEV" "$ROOT_VOL" "$TEST_SUBVOL_NAME" "$TEST_SUBVOL"

      - name: Add testdata to the subvolume
        run: sudo .github/output_content_to_file.sh "$CONTENT" "$TEST_SUBVOL/file.txt"

      - name: Install restic
        run: |
          sudo apt-get update && sudo apt-get install -y restic

      - name: Initialise restic repo
        # location & password come from the RESTIC_* environment variables
        run: |
          restic init

      - name: Set up systemd services
        run: |
          sudo mkdir -p /usr/local/lib/systemd/system/
          sudo mkdir -p /usr/local/bin
          sudo cp systemd/*.service /usr/local/lib/systemd/system/
          sudo cp scripts/*.sh /usr/local/bin
          
          sudo mkdir /usr/local/lib/systemd/system/btrfs-restic-backup.service.d
          sudo tee /usr/local/lib/systemd/system/btrfs-restic-backup.service.d/env.conf << EOF
          [Service]
          Environment="BTRFS_SUBVOL=$TEST_SUBVOL"
          Environment="BACKUP_PATHS=$TEST_SUBVOL"
          Environment="RESTIC_REPOSITORY=$RESTIC_REPOSITORY"
          Environment="RESTIC_PASSWORD=$RESTIC_PASSWORD"
          # alter content of test file to verify the snapshot is being backed up
          ExecStartPre=${{ github.workspace}}/.github/output_content_to_file.sh foo $ROOT_VOL/$TEST_SUBVOL_NAME/file.txt
          ExecStart=/usr/bin/echo visual-confirmation-that-this-happens-after-exec-start-in-main-service
          EOF
          
      - name: Run unit to backup subvolume
        run: .github/run_and_wait_for_unit_to_finish.sh btrfs-restic-backup.service

      - name: Verify backed up contents
        run: .github/verify_backed_up_content.sh "$TEST_SUBVOL/file.txt" "$CONTENT"

      - name: Verify existing contents
        run: .github/verify_content.sh "$TEST_SUBVOL/file.txt" "foo"

      - name: Delete subvolume including test data
        run: .github/delete_btrfs_subvolume.sh "$ROOT_VOL" "$TEST_SUBVOL_NAME" "$TEST_SUBVOL"

      - name: Restore from backup
        run: sudo --preserve-env scripts/btrfs-restic-restore.sh

      - name: Verify restored contents
        run: .github/verify_content.sh "$TEST_SUBVOL/file.txt" "$CONTENT"

      - name: Check check was run
        run: ls -l /var/lib/btrfs-restic-backup.service
