name: ci.yml
on:
  push: {}

jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      FAKE_DEV: /dev/fake-dev0
      ROOT_VOL: ${{ github.workspace }}/.root
      TEST_SUBVOL: ${{ github.workspace }}/.subvol
      TEST_SUBVOL_NAME: ".subvol"
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: 'false'

      - name: Create virtual block device
        run: .github/create_block_device.sh "$RUNNER_TEMP/dev0-backstore" "$FAKE_DEV"

      - name: Create BTRFS volume
        run: .github/create_btrfs_volume.sh "$FAKE_DEV" "$ROOT_VOL"

      - name: Create BTRFS subvolume
        run: .github/create_btrfs_subvolume.sh "$FAKE_DEV" "$ROOT_VOL" "$TEST_SUBVOL_NAME" "$TEST_SUBVOL"

      - name: Add testdata to the subvolume
        run: |
          echo "hello, world" | sudo tee "$TEST_SUBVOL/file.txt"

# TODO
#      - name: Install restic
#        run: |
#          sudo apt-get update && sudo apt-get install -y restic

      - name: Set up systemd services
        run: |
          mkdir -p ~/.config/systemd/user
          mkdir -p /usr/local/bin
          cp systemd/*.service ~/.config/systemd/user
          cp scripts/*.sh /usr/local/bin
          
          mkdir ~/.config/systemd/user/btrfs-restic-backup.service.d
          cat > ~/.config/systemd/user/btrfs-restic-backup.service.d/env.conf<< EOF
          [Service]
          Environment="BTRFS_VOL=$ROOT_VOL"
          Environment="BTRFS_SUBVOL=$TEST_SUBVOL"
          Environment="BTRFS_DEVICE=$FAKE_DEV"
          Environment="BACKUP_PATHS=$TEST_SUBVOL"
          EOF
          
      - name: Run unit to backup subvolume
        run: .github/run_and_wait_for_unit_to_finish.sh btrfs-restic-backup.service
